### ISSUE TITLE
Pytorch Tensor with bf16 data

### ISSUE THREAD

**Issue by isVoid** [NVIDIA/numbast#34]
When tensors passed to Numba kernels, it converts into cuda_array_interface. We need make sure the data type that's received matches with the bf16 data type from Numbast.

**Comment by quasiben** [comment]
My guess is this test isn't totally valid but did show an interesting issue we need to resolve:


```python

def test_torchbf16():
    torch = pytest.importorskip("torch")

    @cuda.jit(link=["bf16_shim.cu"])
    def torch_add(a, b, out):
        out = a + b


    a = torch.ones([2,2], device=torch.device('cuda:0'), dtype=torch.bfloat16)
    b = torch.ones([2,2], device=torch.device('cuda:0'), dtype=torch.bfloat16)
    out = torch.zeros([2,2], device=torch.device('cuda:0'), dtype=torch.bfloat16)

    res = torch_add[2, 2](a, b, out)
```

Numba uses the [__cuda_array_interface__](https://github.com/numba/numba/blob/9ce83ef5c35d7f68a547bf2fd1266b9a88d3a00d/numba/cuda/api.py#L80-L85) if an obj is a CUDA obj.  PyTorch will check the dtype of that object in the [following code](https://github.com/pytorch/pytorch/blob/0f6ce45bcbd7026c00da43db0317ede10830378b/torch/_tensor.py#L1167-L1178)

The above tests fails because `torch.bfloat16` is not a valid key:

```
>       typestr = {
            torch.complex64: "<c8",
            torch.complex128: "<c16",
            torch.float16: "<f2",
            torch.float32: "<f4",
            torch.float64: "<f8",
            torch.uint8: "|u1",
            torch.int8: "|i1",
            torch.int16: "<i2",
            torch.int32: "<i4",
            torch.int64: "<i8",
        }[self.dtype]
E       KeyError: torch.bfloat16

../../miniconda3/envs/numbast/lib/python3.11/site-packages/torch/_tensor.py:1167: KeyError
```

Some options here include adding support for bf16 in the cuda_array_interface and/or special casing support within numba.

**Comment by gmarkall** [comment]
That's also going to fail because you can't write array expressions in CUDA kernels. It will need to be something like:

```python
@cuda.jit(link=["bf16_shim.cu"])
def torch_add(a, b, out):
    i = cuda.grid(1)
    if i < len(out):
        out[i] = a[i] + b[i]
```

**Comment by quasiben** [comment]
Another option would be to use DLPACK ([bf16 support](https://dmlc.github.io/dlpack/latest/c_api.html#c.DLDataTypeCode.kDLBfloat)) instead of/in addition to CAI in Numba.  Though that may be very big lift

**Comment by isVoid** [comment]
How about piggy back on jax [ml_dtype](https://github.com/jax-ml/ml_dtypes)? Can we some how "trick" Numba in believing that it is a legit Numpy dtype? Currently:

```python
@cuda.jit
def kernel(arr):
    arr[0] = 1.0


arr = np.zeros(1, dtype=bfloat16)
kernel[1, 1](arr)
```
  File "/home/wangm/mambaforge/envs/numbast/lib/python3.11/site-packages/numba/core/typing/typeof.py", line 248, in _typeof_ndarray
    raise errors.NumbaValueError(f"Unsupported array dtype: {val.dtype}")
numba.core.errors.NumbaValueError: Unsupported array dtype: bfloat16
```

**Comment by isVoid** [comment]
Trying to patch `FROM_DTYPE` here: 

```python
FROM_DTYPE[np.dtype("bfloat16")] = nv_bfloat16.nb_type


@cuda.jit(link=["bf16_shim.cu"])
def kernel(arr):
    arr[0] = nv_bfloat16(1.0)


arr = np.zeros(1, dtype=np.dtype("bfloat16"))
kernel[1, 1](arr)
```

And it seems like we are getting closer:
```
  File "/home/wangm/mambaforge/envs/numbast/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py", line 3127, in host_to_device
    fn(device_pointer(dst), host_pointer(src, readonly=True), size, *varargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangm/mambaforge/envs/numbast/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py", line 3042, in host_pointer
    return mviewbuf.memoryview_get_buffer(obj, forcewritable, readonly)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot include dtype 'E' in a buffer
```

This is likely because this new dtype string introduced in ml_dtype that's not recognized by the driver.
https://github.com/jax-ml/ml_dtypes/blob/9fc7e6773acb66fa496ed8d476a008a489a4da49/ml_dtypes/_src/dtypes.cc#L58

**Comment by isVoid** [comment]
Additional patches in `driver.py`, WAR to view bfloat16 with `np.float16` (I think it's fine since they should share the same size and alignment).

```
diff --git a/driver.py b/home/wangm/mambaforge/envs/numbast/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py
index ee2f5ad..ed6e3ce 100644
--- a/driver.py
+++ b/home/wangm/mambaforge/envs/numbast/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py
@@ -3013,6 +3013,13 @@ def _is_datetime_dtype(obj):
     return dtype is not None and dtype.char in 'Mm'
 
 
+def _is_mldtype_bfloat16(obj):
+    """Returns True if the obj.dtype is bfloat16
+    """
+    dtype = getattr(obj, 'dtype', None)
+    return dtype is not None and dtype.char in 'E'
+
+
 def _workaround_for_datetime(obj):
     """Workaround for numpy#4983: buffer protocol doesn't support
     datetime64 or timedelta64.
@@ -3022,6 +3029,14 @@ def _workaround_for_datetime(obj):
     return obj
 
 
+def _workaround_for_mldtype_bfloat16(obj):
+    """Workaround for unsupported ml_dtypes.bfloat16
+    """
+    if _is_mldtype_bfloat16(obj):
+        obj = obj.view(np.float16)
+    return obj
+
+
 def host_pointer(obj, readonly=False):
     """Get host pointer from an obj.
 
@@ -3039,6 +3054,7 @@ def host_pointer(obj, readonly=False):
         forcewritable = isinstance(obj, np.void) or _is_datetime_dtype(obj)
 
     obj = _workaround_for_datetime(obj)
+    obj = _workaround_for_mldtype_bfloat16(obj)
     return mviewbuf.memoryview_get_buffer(obj, forcewritable, readonly)
```

This seems to have made the above example work.

**Comment by isVoid** [comment]
Getting torch to support ml_dtype's bfloat16 looks like the next step, and torch team seems to be OK with it.
https://github.com/pytorch/pytorch/issues/109873

Additionally I noticed that current pytorch version only works with CTK12.1, and I recall Numbast bfloat16 bindings is not fully working with 12.1 (to be checked). Release 2.4 is [coming out in May](https://dev-discuss.pytorch.org/t/release-cadence-for-year-2023-2024/1557), where [12.4 support](https://github.com/pytorch/pytorch/issues/123456) will be added.

**Comment by gmarkall** [comment]
I had a prototype of some typing work in https://github.com/gmarkall/numba-bfloat16/blob/main/prototype.py - the `bfloat16` library it refers to is https://github.com/GreenWaves-Technologies/bfloat16, which was pulled out from the Tensorflow bfloat16 implementation.

**Comment by isVoid** [comment]
> Another option would be to use DLPACK ([bf16 support](https://dmlc.github.io/dlpack/latest/c_api.html#c.DLDataTypeCode.kDLBfloat)) instead of/in addition to CAI in Numba. Though that may be very big lift

How big of a lift it is? Just spoke with @leofang and it may be some lift, but could relatively small comparing to getting torch to adopt `ml_dtypes`, but I could be wrong.

**Comment by quasiben** [comment]
`nb_type`  is not available for me.  Was this recently added ?

```
In [9]: from bf16 import nv_bfloat16

In [10]: nv_bfloat16.nb_type
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[10], line 1
----> 1 nv_bfloat16.nb_type

AttributeError: type object '__nv_bfloat16' has no attribute 'nb_type'
```

**Comment by gmarkall** [comment]
Where does the expectation of the existence of `nb_type` come from? (I've never heard of this)

**Comment by isVoid** [comment]
> Where does the expectation of the existence of `nb_type` come from? (I've never heard of this)

Ah, when experimenting this locally, I added this attribute to inspect the numba type of a new binding. But when pushing it to `main`, I renamed it to `_nb_type`.
